# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3-rc-3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.5.5
maven_group=com.operationpotato
archives_base_name=hypixel-tab-completions

# Multiversion Properties
primary_mc_version=26.3
mc_range=~26.3-
minimum_fabric_api_version=0.144.0+26.1

# Dependencies
fabric_api_version=0.160.4+26.3
fabric_kotlin_version=1.13.8+kotlin.2.3.0
hm_api_version=1.0.4+26.3-rc-2
dev_auth_version=1.2.2
